a=input()
b=input()
c=input()
prop = int(a)*int(b)*int(c)
pro = str(prop)
print(pro.count('0'))
print(pro.count('1'))
print(pro.count('2'))
print(pro.count('3'))
print(pro.count('4'))
print(pro.count('5'))
print(pro.count('6'))
print(pro.count('7'))
print(pro.count('8'))
print(pro.count('9'))